import java.text.DecimalFormat;
public class BMIJF extends javax.swing.JFrame
{
    private double weight,height,BMI;
    private String name,healthadvices;
    private int age;
    private String healthadvices1,healthadvices2,healthadvices3,healthadvices4,healthadvices5,healthadvices6,
            healthadvices7,healthadvices8,healthadvices9,healthadvices10,healthadvices11,healthadvices12,healthadvices13,healthadvices14;
    
    
    public BMIJF()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        Weight = new javax.swing.JTextField();
        Height = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        sajasaja = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Candara", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BMI Calculator and Health Advices System");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Age : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Weight (kg) : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Height (m) : ");

        Name.setBackground(new java.awt.Color(255, 204, 204));
        Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Age.setBackground(new java.awt.Color(255, 255, 153));
        Age.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Age.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Weight.setBackground(new java.awt.Color(153, 255, 153));
        Weight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Weight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Weight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Height.setBackground(new java.awt.Color(153, 153, 255));
        Height.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Height.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Height.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 51));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Weight, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Height, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sajasaja, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sajasaja, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Weight, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Height, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Name.setText("");
        Age.setText("");
        Weight.setText("");
        Height.setText("");
        //HealthAdvices.setText("");
        //result.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         //try
     //   {
            weight = Double.parseDouble(Weight.getText());
            height = Double.parseDouble(Height.getText());
            
            //calculation
            BMI = weight / ( height * height ); 
            
            String stringBMI = Double.toString(BMI);
            
            if (BMI < 18.5)
            {
                healthadvices1 = ("BMI Classification: Underweight");
                healthadvices2 = ("What happens when one is underweight?");
                healthadvices3 = ("1. Underweight increase one’s risk of health problems.");
                healthadvices4 = ("2. Being underweight is linked with heart problems, lowered resistance to infection, chronic fatigue and etc.");
                healthadvices5 = ("");
                healthadvices6 = ("How does one gain weight in a healthy way?");
                healthadvices7 = ("1. Aim for a gradual weight gain, which should be about 1 to 2 kilogram per month. You should aim for a BMI between 18.5 and 24.9 kg/m");
                healthadvices8 = ("2. Practise healthy eating, practice choose and eat a variety of foods daily as guided by the Malaysian Food Pyramid.");
                healthadvices9 = ("3. Avoid skipping meals.");
                healthadvices10 = ("4. Plan ahead for extra meals. To gain weight, you may need to eat more nutritions foods.\n");
                healthadvices11 = ("5. Snack smartly by choosing nutrient-densed snacks that add calories, vitamins and minerals.\n");
                healthadvices12 = ("6. Check your energy requirement. Don’t forget that you need to indicate what your physical activity level is in order to calculate your daily energy requirement.\n");
                healthadvices13 = ("7. Refer to the sample menu. Choose the menu that suits your daily calorie requirement.");
            }
            
            else if ((BMI >= 18.5) && (BMI < 25))
            {
                healthadvices1 = ("BMI Classification: Normal\n");
                healthadvices2 = ("What is a healthy weight?\n");
                healthadvices3 = ("1. A healthy weight falls within BMI of 18.5 to 24.9 kg/m²\n");
                healthadvices4 = ("2. Studies have shown that people whose BMI are within this range tend to live longer than people who have lower or higher BMI.\n");
                healthadvices5 = ("");
                healthadvices6 = ("How to maintain normal body weight?\n");
                healthadvices7 = ("1. Balance the food that you eat with physical activity.\n");
                healthadvices8 = ("2. Do more physical activity. If you are already very active, try to continue the same level of activity suitable to your age.");
            }
    
            else if ((BMI >= 25.0) && (BMI < 30))
            {
                healthadvices1 = ("BMI Classification: Overweight\n");
                healthadvices2 = ("When is one considered overweight?\n");
                healthadvices3 = ("1. You are overweight if your BMI is between 25.0 to 30.0\n");
                healthadvices4 = ("How can you lose weight?\n");
                healthadvices5 = ("1. Weight yourself once a week, preferably before meal.\n" );
                healthadvices6 = ("2. Set a realistic target to reduce half kilogram of body weight per week.\n");
                healthadvices7 = ("3. Check your energy requirement.\n");
                healthadvices8 = ("4. Eat normal, reasonable, moderate amounts of nutritious foods based on the Malaysian Food Pyramid.\n");
                healthadvices9 = ("5. Don’t ever diet or restrict calories when you are really hungry. If you do, you will tend to binge later.\n");
                healthadvices10 = ("6. Do some diet modification.\n");
                healthadvices11 = ("7. Reduce or avoid foods high in sugar and fat such as butter, cream, fatty meat, salad dressing, rich cake and pastries.\n");
                healthadvices12 = ("8. Consult the dietician or nutritionist for further weight management.\n");
                healthadvices13 = ("9. Consult a doctor to identify and correct any underlying medical, biological, or physiological problems contributing to excess weight.\n");
                healthadvices14 = ("10. Find a support system. Friends are great; so are support groups.");
            }
    
            else
            {
                healthadvices1=("BMI Classification: Obese\n");
                healthadvices2=("When is one considered obese?\n");
                healthadvices3=("1. You are obese if your BMI is 30 or more.\n");
                healthadvices4=("How can you lose weight?\n");
                healthadvices5=("1. Weight yourself once a week, preferably before meal.\n" );
                healthadvices6=("2. Set a realistic target to reduce half kilogram of body weight per week.\n" );
                healthadvices7=("3. Check your energy requirement.\n");
                healthadvices8=("4. Eat normal, reasonable, moderate amounts of nutritious foods based on the Malaysian Food Pyramid.\n");
                healthadvices9=("5. Don’t ever diet or restrict calories when you are really hungry. If you do, you will tend to binge later.\n");
                healthadvices10=("6. Do some diet modification.\n");
                healthadvices11=("7. Reduce or avoid foods high in sugar and fat such as butter, cream, fatty meat, salad dressing, rich cake and pastries.\n");
                healthadvices12=("8. Consult the dietician or nutritionist for further weight management.\n");
                healthadvices13=("9. Consult a doctor to identify and correct any underlying medical, biological, or physiological problems contributing to excess weight.\n");
                healthadvices14=("10. Find a support system. Friends are great; so are support groups.");
            }
                //new InterfaceResult(aju, mag).setVisible(true);*/
                
                new ResultAndHealthAdvises(stringBMI,healthadvices1,healthadvices2,healthadvices3,healthadvices4,healthadvices5
                ,healthadvices6,healthadvices7,healthadvices8,healthadvices9,healthadvices10,healthadvices11,healthadvices12,healthadvices13,healthadvices14).setVisible(true);
            

       
       // catch (Exception e)
       // {
       //     HealthAdvices.setText("Please check required textfields!");
      //  }
    }//GEN-LAST:event_jButton2ActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMIJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMIJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMIJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMIJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new BMIJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JTextField Height;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Weight;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel sajasaja;
    // End of variables declaration//GEN-END:variables
}